-- Crear la tabla users
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN NOT NULL,
    email VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL
);

-- Inserción de usuarios
INSERT INTO users (active, email, username) VALUES
(true, 'user1@example.com', 'user1'),
(true, 'user2@example.com', 'user2');
